### ISSUE TITLE
path.existsSync is now called `fs.existsSync`.

### ISSUE THREAD

**Issue by JacksonGariety** [gatapia/nclosure#18]
I get this warning when starting my node app.

This should be changed. I'm not sure what the line number is.

**Comment by wimpyprogrammer** [comment]
I've submitted #22 to address this.  The `path.exists` and `path.existsSync` deprecated functions were recently removed, so the behavior has changed from a warning to a fail.  Though I'm not sure if anyone is still maintaining this repository.
